[package]
name = "stellarust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "frontend",
    "backend",
    "data-model",
    "clausewitz-parser"
]

[dependencies]
time = {version = "0.3.5", features = ["serde"]}
serde = {version = "1.0.132", features=["derive"]}
strum = "0.23.0"
strum_macros = "0.23.1"

[dev-dependencies]
wasm-bindgen-test = "0.3.28"
fantoccini = "0.17.5"
tokio = { version = "1.15.0", features = [ "full" ] }
anyhow = "1.0.51"