[package]
name = "stellarust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "frontend",
    "backend"
]

[dev-dependencies]
wasm-bindgen-test = "0.3.28"
fantoccini = "0.17.5"
tokio = { version = "1.14.0", features = [ "full" ] }