[package]
name = "unzipper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
zip = "0.5.13"

[dev-dependencies]
path-test-helper = {version = "0.1.0", path = "../path-test-helper"}