[package]
name = "data-core-mock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data-core = {version = "0.1.0", path ="../data-core"}